### ISSUE TITLE
Clear up a few issues regarding elementaryOS

### ISSUE THREAD

**Issue by electricduck** [sodaliterocks/sodalite#13]
It would be best to clear the air between Sodalite and elementaryOS, to make sure there's no treading on toes and no confusion of users. Although this project is currently quite small it would be a good idea to sort these issues out from the get-go. Things we need to discuss:

- [x] Are we allowed to pack the AppCenter Flatpak repository by default into the OS?
  - As we are using GNOME Software currently (boo!), the pay-what-you-want system is being circumvented and developers are possibly losing out on potential sales. In the future I would like AppCenter to be working on Sodalite along with the payment system.
  - If we're not allowed, could we do this as an optional thing during on-boarding since curated apps are an important part of elementary, but still letting the user know about the pay-what-you-want system somehow?
- [x] What's the best way to refer to the DE?
  - In documentation it would be nice to always mention the DE is "Pantheon" and not "elementary", but there doesn't seem to be a canonical link to Pantheon on elementary's website to explain the DE to users: it's all just elementary(OS).
  - We could make our own explanation of Pantheon?
- [x] Making sure to send beginner users to elementaryOS instead, as Sodalite is far from finished and targets more novice users.
- [ ] Potentially out-of-scope, it would be nice to make sure Sodalite-specific issues are not posted in elementary's subreddit or other discussion areas.
- [x] Are we breaking any other licensing issues with elementary?
- [x] Any other potential issues?

Would be nice to get appropriate people from elementary on this (@cassidyjames? @danrabbit?).

**Comment by danrabbit** [comment]
Sure you can pre-install the AppCenter remote that's not a problem. We're working on a cross-platform payment solution.

Yes the desktop environment is called Pantheon. The only real reference we have of it on our website is on our open source page: https://elementary.io/open-source

If you're concerned about infringing on trademark/licensing you'll need to consult a lawyer. We're not able to answer legal questions or give legal advice. What I can tell you is that Pantheon is available under the terms of various GPL licenses as described in their respective source code repositories, but our trademarks used in commerce (the elementary "e", the elementary workmark, etc) are not openly licensed.

**Comment by electricduck** [comment]
> Sure you can pre-install the AppCenter remote that's not a problem. We're working on a cross-platform payment solution.

That's great to hear!

> Yes the desktop environment is called Pantheon. The only real reference we have of it on our website is on our open source page: https://elementary.io/open-source

Hm, alright. Suppose I could do a little bit of explianing in the docs of what Pantheon is and how it differs from elementaryOS. Although, tbf, the users using this should already be aware of the differences :thinking:.

Thanks for the input :smile:.

**Comment by cassidyjames** [comment]
Also be sure to read through the brand page on the elementary website if you haven't for clarity in usage of the elementary names and marks:

https://elementary.io/brand
