### ISSUE TITLE
No refs in new OSTree remote

### ISSUE THREAD

**Issue by jadeastar** [sodaliterocks/sodalite#20]
```
[jae@rhenium ~]$ sudo ostree pull sodalite:sodalite/stable/x86_64/stable

error: Not normal form
[jae@rhenium ~]$ sudo rpm-ostree rebase sodalite:sodalite/stable/x86_64/stable
error: While pulling sodalite/stable/x86_64/stable: Not normal form
[jae@rhenium ~]$ 

```

**Comment by ACertainTopfi** [comment]
Could you post what the terminal provides when executing `ostree remote list` and `ostree remote show-url`?

**Comment by jadeastar** [comment]
> ~Could you post what the terminal provides when executing `ostree remote list` and `ostree remote show-url`?~ I think I know the issue. It's `sodalite/stable/x86_64/base`, not `sodalite/stable/x86_64/stable`.

Nope, it was missing both ways, just used the old URL

**Comment by electricduck** [comment]
Ah, hm, this is one of those things I would assume would just work. Silly me!

Apparently it seems `ostree` doesn't follow redirects. To fix this, I've just pointed the root [on the server] to the same directory `https://ostree.zio.sh/repo` hosts. Not entirely sure why I didn't do this in the first place :man_facepalming:.

Verified it on my own machine with `ostree remote refs sodalite` and this is the output:

```
sodalite:fedora/35/x86_64/sodalite
sodalite:sodalite/stable/x86_64/base
```

**Comment by jadeastar** [comment]
I'll do some testing in a bit. Just wanna say, OSTree distro dev to OSTree distro dev, I appreciate the work and if you ever need anything just let me know :)

**Comment by electricduck** [comment]
Hah, you know the open-source world: help is **always** needed :laughing:. PRs are more than welcome.

**Comment by jadeastar** [comment]
Thanks :)
