### ISSUE TITLE
Version Numbering

### ISSUE THREAD

**Issue by ACertainTopfi** [sodaliterocks/sodalite#21]
Currently, Sodalite has no defined standard for version numbering. There are a few ways this could be addressed.

1. We could simply utilize the same version numbering system employed by Fedora, starting with Sodalite 35
2. We could start with yearly numbering (i.e. 21.2 for a build based on Fedora 35 and 22.1 for a build based on Fedora 36)
3. We could use a similar system to Elementary OS, starting with a few beta releases before changing over to full numbers

I see each of these having their own up- and downsides and am not personally partial to any one.

**Comment by electricduck** [comment]
This was actually done two releases ago, and it is described as such (https://github.com/sodaliterocks/sodalite/releases/tag/v%2Fstable%2F35-22.0). It just needs adding to the README.

**Comment by ACertainTopfi** [comment]
Sorry, missed that.
