### ISSUE TITLE
rpm-ostree install resulting in failure to download gpg key

### ISSUE THREAD

**Issue by sparticvs** [sodaliterocks/sodalite#26]
Greetings. To start, I'm new to rpm-ostree, so it's possible that I am make a simple mistake. I'm trying to install a local RPM via `rpm-ostree install`, however I get the following error:

```
error: Updating rpm-md repo 'rpmfusion-nonfree-nvidia-driver': Failed to download gpg key for repo 'rpmfusion-nonfree-nvidia-driver': Curl error (37): Couldn't read a file:// file for file:///usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-35 [Couldn't open file /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-35]
```

Current status is:
```
State: idle
Deployments:
● sodalite:sodalite/stable/x86_64/base
                   Version: 35-22.6.18 (2022-03-14T00:11:39Z)
                    Commit: 3af99c59f28452c806035f08e2c7a36f699ef54b312ec0c61706760cb25cfba2

  sodalite:sodalite/stable/x86_64/base
                   Version: 35-22.5 (2022-02-09T16:45:00Z)
                    Commit: 3cc2a0ab044d8950ec2bd9465f6be6b13c7e01575a6589ecc2e68a957f2c8798
```

After doing a couple searches, the commonly accepted solution was to `rpm-ostree rebase fedora...`, but I don't have the fedora deployments anymore (I got the idea from following the instructions that needed to be removed). I also have this issue when rolling back to the previous version.

Any suggestions to help me get past this issue would be greatly appreciated.

**Comment by electricduck** [comment]
This is an issue that's cropped up before, and its to do with when selecting third-party repositories on NVIDIA on the initial Fedora Silverblue install. It's something I unfortunately am unable to replicate without obliterating an install I have of it. The easiest workaround is to just remove the offending repository (located in `/etc/yum.repos.d/`), and install the NVIDIA driver with `sodalite-hacks nvidia --install`.

**Comment by sparticvs** [comment]
Thanks electricduck. I will give that a go and report back. Is there a particular file that maybe we could add with some of these FAQs? I'm happy to contribute that.

**Comment by electricduck** [comment]
Mhm, yes, an FAQ was supposed to be on the cards along with a miriad of documents. Personal issues left this project slightly abandoned in the past few weeks, so much so I didn't notice the OS hadn't received updates in a while. Gonna get back onto this though! :smile:.

**Comment by sparticvs** [comment]
That worked for me. I had to remove all of the non-free repos (nvidia and steam).
