### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by glidingthrough** [sodaliterocks/sodalite#31]
Loaded up Sodalite in a VM this morning to find a banner at the top of the Software window stating that my operating system is no longer supported. It said that I was all up-to-date and that I last checked 5 days ago, so I clicked the refresh button which generated the below curl error regarding nvidia drivers.

![image](https://user-images.githubusercontent.com/97669346/171989919-88d407b6-b694-4c03-bad2-2f379ef53788.png)

Steps to reproduce: Install Fedora Silverblue 36 in Gnome Boxes, Update and reboot, install Sodalite, reboot, Check for updates, power off, <leave for 5 days :smile:>, power up Sodalite and check for updates. It happened last week, too, so I reinstalled everything from scratch and it's happening again now :disappointed:

**Comment by electricduck** [comment]
This is when you installed Silverblue and chose the third-party repos, which installs the RPMFusion repo but Sodalite does not include the GPG key. I assume you're wanting that repo due to your Nvidia GPU, so you'll need to remove that repo and package, and you can use `sodalite-hacks nvidia --install` to install it.

**Comment by glidingthrough** [comment]
Duly noted. I removed the steam and nvidia files from the `/etc/yum.repos.d` directory and it all works well again. I chose third-party repos on install with an attitude of 'might need it in the future' rather than out of an existing need. Thanks for your assistance :+1:

**Comment by electricduck** [comment]
Closing this in favour of #33, as this is a re-occuring issue that needs to be resolved.
