### ISSUE TITLE
Namarupa/Wingpanel-Indicator-Ayatana

### ISSUE THREAD

**Issue by TGRush** [sodaliterocks/sodalite#38]
### Something that I have always found lacking in elementaryOS - and by extension Pantheon - was Appindicators/Tray Icons

However, I haven't missed these because they look nice, or are a good solution, but rather because many applications relying on them have no better way to run in the background than this *(Telegram, Nextcloud, Discord, I think even Slack, you name it)*

Thus, I propose either including, or having a way to install [Namarupa](https://github.com/Lafydev/wingpanel-indicator-ayatana) or [Wingpanel-Indicator-Ayatana](https://github.com/Lafydev/wingpanel-indicator-ayatana)

They're practically identical, other than the fact that Namarupa puts them not directly on the panel, but rather in an indicator on the panel (a 3-dot indicator). This provides support for legacy tray icons for applications which need them, without looking out of place on the wingpanel, nor taking up too much space

Even though Namarupa has not been updated in a while, it still works just fine on my ElementaryOS installation (6.1), and Wingpanel-indicator-Ayatana also still works

*(Note that Wingpanel-Indicator-Ayatana used to be the official implementation until 2017, and it has been community-maintained until 2021)*

**Comment by electricduck** [comment]
I'll dig into this again, but I seem to remember dropping it quite some time ago due to some missing dependencies in Fedora (since Wingpanel-Indicator-Ayatana **used** to be available in the [elementary-staging](https://copr.fedorainfracloud.org/coprs/decathorpe/elementary-staging/) repo).

**Comment by electricduck** [comment]
**Wingpanel-Indicator-Ayatana** is now back once more in `main` and will be in the next release.

![image](https://user-images.githubusercontent.com/1594644/190048560-ce812d9e-b810-47e7-81bc-5868a4b7d7a2.png)

**However**, considering `indicator-application` is essentially abandoned, and Namarupa and Ayatana both don't seem to in active development, there's no real gurantee of how long it'll work for. But it seems to work properly for now!
