### ISSUE TITLE
Locales aren't being set correctly

### ISSUE THREAD

**Issue by TGRush** [sodaliterocks/sodalite#40]
The OS is currently not only missing it's locale options in switchboard, but even when set manually through CLI, most of the OS doesn't adhere to the language and is still displayed in English

For anyone with another mother language than English, this can be quite frustrating. Thus I would like to see it fixed in the future

*(This happened across multiple devices on F36 Sodalite)*

**Comment by electricduck** [comment]
Unfortunately, the upstream Locale Switchboard item is practically hardcoded to only work with Ubuntu and is entirely broken outside of Ubuntu.

Interested to know what command you used to change the locale however?

**Comment by TGRush** [comment]
> Unfortunately, the upstream Locale Switchboard item is practically hardcoded to only work with Ubuntu and is entirely broken outside of Ubuntu.
> 
> Interested to know what command you used to change the locale however?

after some digging on the internet, I stumbled upon `localectl`, which allowed me to set the language even after install :P

**Comment by electricduck** [comment]
Ah, I see, `localectl` will only affect the system locale. You also need to adjust the value in two other areas (as far as I'm aware):

 1) Open a shell.
 2) Adjust the locale for your account via AccountService, which will adjust it for supported CLI tools and various GUI applications
    1) Open `/var/lib/AccountsService/users/$user` in an editor<br />_(e.g. `sudo nano /var/lib/AccountsService/users/$user`)_
    2) Edit the value of `Language` under `[User]` to the locale of your choice, similar to what you set with `localectl`
 3) Adjust the locale for GNOME (which Pantheon rides on) via GSettings, which will adjust it for various supported GTK applications
    1) `gsettings set org.gnome.system.locale region <locale>`
 4) Logout and login (or `sudo systemctl restart lightdm`)

**Comment by electricduck** [comment]
This is now partially fixed: changing the locale with `localectl` will now affect the desktop (after logging out and logging in). Unfortunately, we still don't have a GUI way of doing this as the Locale Switchboard plug relies exclusively on `apt`.
