### ISSUE TITLE
Abandon 37 (Is this the end?)

### ISSUE THREAD

**Issue by electricduck** [sodaliterocks/sodalite#44]
https://www.spinics.net/lists/fedora-devel/msg304445.html

Having been out-of-the-loop for some time, this has only just now been brought to my attention (TL;DR there is no way Pantheon can be supported for Fedora 37 as of currently, possibly even Fedora 38). With that in mind, **I am going to abandon the 37 release** (removing branches, etc.). Currently, 37 was being built by using old repositories for 36 &mdash; as I was unaware of what was going on &mdash; but this is a truely awful hack that will break someday and I am unwilling to allow to be production.

These tasks need doing:

- [x] Return `main` branch to 36 (currently 37)
- [x] Remove `release/f37` branch
- [x] Remove all current tags for `v/f37/37-xx.xx`
- [x] Stop builds of `sodalite/f37/<arch>/<edition>` on the build server
- [x] Remove all builds of `sodalite/f37/<arch>/<edition>` on the build server

As it stands, the fate of Sodalite rests in limbo, as I too do not have the capacity to invest in getting Pantheon working on Fedora 37+: a real bummer for me since Sodalite is my daily. The good news is 36 will continue to be supported until 14-Nov-2023, so hopefully something can be resolved by this time.

Development for 38+ will still continue in `release/next` by retaining the current ugly using-36-repositories hack), but bear in mind this will break someday until the main issue is resolved, and on that day builds will stop and releases won't be tagged.

Stay tuned.

**Comment by electricduck** [comment]
All tasks completed. Closing issue, but keeping it pinned.

**Comment by akatsukilevi** [comment]
Could it be that, once the eOS 7 is released, they shift focus into fixing compatibility with libsoup2 to libsoup3 which could help with the broken state of Pantheon on Fedora? Don't even know if eOS even uses libsoup? Will search it up and edit this comment once I'm back

**Comment by electricduck** [comment]
Some apps require an older version of `evolution-data-server` which uses `libsoup2`. See: 
 * https://github.com/elementary/mail/issues/793
 * https://github.com/elementary/mail/issues/793

The main problem is not so much the apps, since we could start just using Flatpak versions, but the lack of support for `libmutter-11` which powers Gala, Greeter, and Wingpanel. 

See: 
 * https://github.com/elementary/gala/issues/1447
 * https://github.com/elementary/greeter/issues/617
 * https://github.com/elementary/wingpanel/issues/462

Theres also a bunch of apps that require older versions of `libwebkit`.

Gotta keep in mind eOS sticks to an LTS version of Ubuntu, so it can easily stay using old packages for years at a time. However, eOS 7 is due to use Ubuntu 22.04. All these referenced issues are open and some are being worked on but none will be finished in time for 37.

**Comment by akatsukilevi** [comment]
For Gala I saw there is a pending PR related to mutter-11(https://github.com/elementary/gala/pull/1457), but haven't seen anything with greeter and wingpanel.

Will try to fork it at weekend and see if I can try to somehow help with the issues, maybe at least fixing the mutter compatibility issue may help

**Comment by decathorpe** [comment]
Yeah, I feel bad about the situation 😞  The desktop components (gala, wingpanel, greeter) were neither build-able nor install-able on Fedora 37 due to the bi-annual mutter breakage, which was to be expected. But in addition to that, the changes with GNOME 43 also broke builds / installability about half the desktop applications (mostly due to incompatibilities with libsoup-3, evolution-data-server 3.45+, webkitgtk-4.1, ...).

I didn't want Fedora 37 to ship with the packages in this sad state, so the only reasonable thing I could do was to remove the packages from Fedora 37+, at least temporarily.

There's two factors that make this development cycle particularly bad - the big underlying changes in GNOME 43, and the slower-than-usual upstream development due to financial problems / reduced full-time staff / focus of their work on getting elementary OS 7 out ... and given that elementary OS 7 will (probably? unless the release is delayed even further ...) be based on ubuntu 22.04, porting projects to versions of GNOME libraries that will only affect them in 18 months is obviously low priority.

**Comment by akatsukilevi** [comment]
Until then sadly not much that can be done

Still going to see if I can try to at least get it to build(even if by using flextape lol) on 37 and how broken it is

In the meantime still going to daily drive Fedora 36, as I believe it won't be breaking overnight. Hopefully we can think on something while Sodalite is still working fine

**Comment by electricduck** [comment]
> In the meantime still going to daily drive Fedora 36, as I believe it won't be breaking overnight. Hopefully we can think on something while Sodalite is still working fine

Like to point out my production machine is running on the `f35` branch (`fedora/f35/x86_64/base`), basically meaning its still running on Fedora 35, and I haven't really run into any problems being slightly behind major Fedora releases. Most of my apps are coming from Flatpak, and I'm doing development in `distrobox`, so no biggy on potentially outdated libraries. Probably will be kept that way until November when its EoL.

So yes, 36 should be fairly usable until late next year.

**Comment by akatsukilevi** [comment]
And hopefully late next year we might have something that we can do about Sodalite that could hopefully bring it to F37

**Comment by pieckenst** [comment]
Seems like there were some fixes added for new mutter in https://github.com/elementary/wingpanel/pull/465
https://github.com/elementary/gala/pull/1457
https://github.com/elementary/greeter/pull/621

**Comment by pieckenst** [comment]
So there should be only the matter of elementary apps now that block fedora 37

**Comment by electricduck** [comment]
> So there should be only the matter of elementary apps now in terms of using pantheon on fedora 37

In terms of apps, we can live without native versions as the next version of Sodalite (36-23.0) will finally begin using elementary's Flatpak apps (of which there are only a few right now -- the rest will stay as the natively installed versions until they become available as Flatpaks) with thanks to a new migration tool which will do all the heavy lifting.

**Comment by electricduck** [comment]
Don't get too excited yet as its not feature-complete, but thanks to [Terra](https://github.com/terrapkg) (thanks @lleyton and @windowsboy111) we might have a potential 37 after all...

![image](https://user-images.githubusercontent.com/1594644/210465469-a1e85601-21a1-4361-81ca-2ebd7372b734.png)

However, the `switchboard-plug-useraccounts` package (which comes from [elementary-staging](https://copr.fedorainfracloud.org/coprs/decathorpe/elementary-staging/)) had to be removed in order to get a build working, otherwise this error occurs during build:

```
error: Could not depsolve transaction; 2 problems detected:
[...]
 Problem 2: conflicting requests
  - nothing provides libgnome-desktop-3.so.19()(64bit) needed by switchboard-plug-useraccounts-2.4.2-1.fc37.x86_64
```

As Terra is also providing much newer packages than currently exists on Fedora 36's repositories, it'll also need a thorough test before I even consider shipping it.

**Comment by pieckenst** [comment]
i hope the terra thing does work out:) I'll wait for updates on whatever the further testing thing might involve

**Comment by electricduck** [comment]
> how would i go about rebasing my fedora silverblue 37 install to this new experimental branch if i were to try it?

You can now test it by pulling `sodalite/f37/x86_64/desktop`

**Comment by pieckenst** [comment]
> > how would i go about rebasing my fedora silverblue 37 install to this new experimental branch if i were to try it?
> 
> You can now test it by pulling `sodalite/f37/x86_64/desktop`.

sudo rpm-ostree rebase sodalite:sodalite/f37/x86_64/desktop
2 metadata, 0 content objects fetched; 0 байт content written
Checking out tree 5a149ee... done
Inactive requests:
  gcc (already provided by gcc-12.2.1-4.fc37.x86_64)
  make (already provided by make-1:4.3-11.fc37.x86_64)
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates rpmfusion-nonfree phracek-PyCharm google-chrome rpmfusion-nonfree-nvidia-driver rpmfusion-nonfree-steam copr:copr.fedorainfracloud.org:rankyn:xivlauncher updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2022-10-06T11:01:40Z solvables: 4
rpm-md repo 'fedora-modular' (cached); generated: 2022-11-10T09:23:24Z solvables: 1454
rpm-md repo 'updates-modular' (cached); generated: 2023-01-03T01:27:52Z solvables: 1464
rpm-md repo 'updates' (cached); generated: 2023-01-10T01:17:16Z solvables: 15367
rpm-md repo 'fedora' (cached); generated: 2022-11-10T09:30:00Z solvables: 66822
rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2023-01-06T18:19:00Z solvables: 148
rpm-md repo 'rpmfusion-free' (cached); generated: 2022-11-11T16:54:42Z solvables: 496
rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2023-01-06T18:39:54Z solvables: 43
rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2022-11-11T17:25:12Z solvables: 218
rpm-md repo 'phracek-PyCharm' (cached); generated: 2022-12-30T11:01:04Z solvables: 5
rpm-md repo 'google-chrome' (cached); generated: 2023-01-05T15:19:40Z solvables: 3
rpm-md repo 'rpmfusion-nonfree-nvidia-driver' (cached); generated: 2023-01-06T19:34:32Z solvables: 30
rpm-md repo 'rpmfusion-nonfree-steam' (cached); generated: 2022-08-24T16:15:54Z solvables: 2
rpm-md repo 'copr:copr.fedorainfracloud.org:rankyn:xivlauncher' (cached); generated: 2023-01-10T03:29:05Z solvables: 6
rpm-md repo 'updates-archive' (cached); generated: 2023-01-10T01:32:46Z solvables: 16587
Resolving dependencies... done
Will download: 2 packages (711,6 кБ)
Downloading from 'fedora'... done
Downloading from 'updates'... done
Importing packages... done
Relabeling... done
Checking out packages... done
error: Checkout libXcursor-1.2.1-2.fc37.i686: Hardlinking c0/274906d6388f6c59c58a08dc9ae6915b763f5cca5a5612ebae6c4450bacda6.file to index.theme: Файл существует
errors out on my end during rebase

**Comment by electricduck** [comment]
> > > how would i go about rebasing my fedora silverblue 37 install to this new experimental branch if i were to try it?
> > 
> > 
> > You can now test it by pulling `sodalite/f37/x86_64/desktop`.
> 
> ```
> sudo rpm-ostree rebase sodalite:sodalite/f37/x86_64/desktop
> 2 metadata, 0 content objects fetched; 0 байт content written
> Checking out tree 5a149ee... done
> Inactive requests:
>   gcc (already provided by gcc-12.2.1-4.fc37.x86_64)
>   make (already provided by make-1:4.3-11.fc37.x86_64)
> Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates rpmfusion-nonfree phracek-PyCharm google-chrome rpmfusion-nonfree-nvidia-driver rpmfusion-nonfree-steam copr:copr.fedorainfracloud.org:rankyn:xivlauncher updates-archive
> Importing rpm-md... done
> rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2022-10-06T11:01:40Z solvables: 4
> rpm-md repo 'fedora-modular' (cached); generated: 2022-11-10T09:23:24Z solvables: 1454
> rpm-md repo 'updates-modular' (cached); generated: 2023-01-03T01:27:52Z solvables: 1464
> rpm-md repo 'updates' (cached); generated: 2023-01-10T01:17:16Z solvables: 15367
> rpm-md repo 'fedora' (cached); generated: 2022-11-10T09:30:00Z solvables: 66822
> rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2023-01-06T18:19:00Z solvables: 148
> rpm-md repo 'rpmfusion-free' (cached); generated: 2022-11-11T16:54:42Z solvables: 496
> rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2023-01-06T18:39:54Z solvables: 43
> rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2022-11-11T17:25:12Z solvables: 218
> rpm-md repo 'phracek-PyCharm' (cached); generated: 2022-12-30T11:01:04Z solvables: 5
> rpm-md repo 'google-chrome' (cached); generated: 2023-01-05T15:19:40Z solvables: 3
> rpm-md repo 'rpmfusion-nonfree-nvidia-driver' (cached); generated: 2023-01-06T19:34:32Z solvables: 30
> rpm-md repo 'rpmfusion-nonfree-steam' (cached); generated: 2022-08-24T16:15:54Z solvables: 2
> rpm-md repo 'copr:copr.fedorainfracloud.org:rankyn:xivlauncher' (cached); generated: 2023-01-10T03:29:05Z solvables: 6
> rpm-md repo 'updates-archive' (cached); generated: 2023-01-10T01:32:46Z solvables: 16587
> Resolving dependencies... done
> Will download: 2 packages (711,6 кБ)
> Downloading from 'fedora'... done
> Downloading from 'updates'... done
> Importing packages... done
> Relabeling... done
> Checking out packages... done
> error: Checkout libXcursor-1.2.1-2.fc37.i686: Hardlinking c0/274906d6388f6c59c58a08dc9ae6915b763f5cca5a5612ebae6c4450bacda6.file to index.theme: File exists
> ```
> 
> errors out on my end during rebase

As this is an environmental issue that I've also come across, I've opened a ticket about `libXcursor` at #53.

**Comment by pieckenst** [comment]
[Screenshot from 2023-01-10 20 25 13](https://user-images.githubusercontent.com/46422808/211620381-531aba2c-909d-498c-a31e-48ebcf817523.png)
Got it installed and working now:) thanks for the help in telegram

**Comment by electricduck** [comment]
Locking this issue in favor of #56 56
