### ISSUE TITLE
Consider using wingpanel-community-indicators instead of wingpanel-indicator-ayatana

### ISSUE THREAD

**Issue by 1280px** [sodaliterocks/sodalite#47]
[This solution](https://github.com/MvBonin/wingpanel-community-indicators), albeit being pretty raw, provides more control for 3rd-party indicators: for instance, unneeded icons can be hidden to the "···" overflow menu, which can be controlled in a [corresponding switchboard plug](https://github.com/MvBonin/switchboard-plug-indicators).

**Comment by electricduck** [comment]
I did initially want to use this, but I seem to recall having some serious issues with it &mdash; which I've stupidly not documented in #38 :facepalm:. I will have another look and report back.

**Comment by electricduck** [comment]
Whatever issue I had doesn't seem to be present anymore, and its right we should be using this over the previous indicators as it doesn't seem to be in activity development anymore. The new indicators will be present in the next version.
