### ISSUE TITLE
docs.sodalite.rocks do not work

### ISSUE THREAD

**Issue by MrGreenTea** [sodaliterocks/sodalite#67]
When I visit http://docs.sodalite.rocks from the Readme I get this error from Cloudflare:

![image](https://user-images.githubusercontent.com/9407731/217561898-e19cc609-05ab-4596-bb30-78b5a6925112.png)

This happens in Firefox and Chrome. When trying to visit with https I also get an SSL Error `SSL_ERROR_NO_CYPHER_OVERLAP`

See [this archived version](https://web.archive.org/web/20230208144124/http://docs.sodalite.rocks/)

**Comment by MrGreenTea** [comment]
Just now I see that there is a second link in the Readme that says that the docs are in progress.

**Comment by electricduck** [comment]
Related to #41. Also going to remove references to it for now since its obviously slightly confusing.
