### ISSUE TITLE
Allow building in a container without sudo

### ISSUE THREAD

**Issue by electricduck** [sodaliterocks/sodalite#93]
Running `build.sh` in container mode (with `--container`) still requires `sudo`. This is unnecessary:
* Podman can run as a normal user
* There is nothing special about the container that would require root access

**Comment by electricduck** [comment]
Podman runs with `--privileged` which needs root privileges to work. Not fixing.

**Comment by sparticvs** [comment]
Can I ask, why is podman running with ```--privileged```?

**Comment by electricduck** [comment]
> Can I ask, why is podman running with `--privileged`?

Unfortunately, `bwrap` fails without it

```⚡ Building tree...
bwrap: Creating new namespace failed: Operation not permitted
error: bwrap test failed, see <https://github.com/coreos/rpm-ostree/pull/429>: bwrap(true): Child process killed by signal 1```

There's an open ticket for Bubblewrap on Docker for this: https://github.com/containers/bubblewrap/issues/505. And according to one comment it does work in an unprivileged Podman, but I've yet to figure out how to do that.
