### ISSUE TITLE
Grab doesnt release: The Grab Is Eternal

### ISSUE THREAD

**Issue by teamcons** [sodaliterocks/sodalite#97]
**What Happened?**

mouse stuck in grab mode :( Cannot do anything else
Not sure if issue due to the base or related to Pantheon itself

**Steps to Reproduce**

Click and hold on the Pantheon top panel. The mouse becomes a grabby hand
Release, wherever, mouse stays grabbed hand. Cannot click anything. Cannot do anything
Only way to revert to normal mouse pointer and behavior is to hit the "Escape" key

**Expected Behavior**

On click release, grabby hand becomes normal mouse.
Any other action can be done from there like clicking on stuff

**OS Version**
Kutai. Current branch.

**Software Version**
Latest release

**Log Output**

idk

### Hardware Info

Puter is an NUC7i3BNK J31188-311
Intel® Core(TM) i3-7100U CPU @ 2.40GHz
Intel(R) HD Graphics 620 (KBL GT2)

**Comment by lcscosta** [comment]
I have the same behavior on my machine running on a fresh install of silverblue and sodalite.
